name: Frontend Tests
on:
  push:
    branches: 
      - main
    paths:
      - frontend/**
  pull_request:
    branches: 
      - main
    paths:
      - frontend/**
defaults:
  run:
    working-directory: frontend
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
